Repository codingo/NoSQLMap, pull requests merged in 2019-05, with the labels that each got.

#81 fixed injectSize type error for Post attacks
  nosqlmap.py
  nsmweb.py
Labels: bug, enhancement

#85 fixed bug postData undefined related issue #83, #84
  nosqlmap.py
Labels: enhancement

#86 Update 'Set App Path' Module to Accept Null Values
  nosqlmap.py
Labels: bug
